### ISSUE TITLE
Mixtape problème

### ISSUE THREAD

**Issue by moncopainal1** [MetaluNetProjects/Homescape#2]
j'ai commencé à interfacer la réécoute des mixtapes, ça marche sur ordi, mais pas sous android, mistère...
Al1

**Comment by Ant1r** [comment]
Je crois que c'est a cause de [split_path], qui n'est pas chargé dans le binaire de homescape (ça vient de hcs je crois).
Il y a une abstraction qq part dans Fraise (et peut-être ailleurs aussi) qui le remplace : [splitpath].

**Comment by moncopainal1** [comment]
J'ai changé de méthode, je pensais que ça venait de readfs, alors j'ai
utilisé des tableaux...
Ça marche presque, mais je n'arrive pas encore à enregistrer le commentaire
en wav, mais ça doit être une connerie...

Le dim. 14 juin 2020 à 23:37, Antoine Rousseau <notifications@github.com> a
écrit :

**Comment by moncopainal1** [comment]
j'ai finalement opté pour des tableaux...

**Comment by moncopainal1** [comment]
ça a l'air de marcher...
