### ISSUE TITLE
latency link domoseq's not working

### ISSUE THREAD

**Issue by moncopainal1** [MetaluNetProjects/Homescape#3]
le bouton lat du domoseq edit n'a pas l'air de marcher...

**Comment by Ant1r** [comment]
j'espère que c'est réglé maintenant.
et j'ai ajouté l'auto-save de la latence.
please confirm it's working for you now!

**Comment by moncopainal1** [comment]
Merci
je m'en va essayer...
Al1

Le dim. 21 juin 2020 à 00:31, Antoine Rousseau <notifications@github.com> a
écrit :

**Comment by moncopainal1** [comment]
Ça marche au poil ! Je constate aussi qu'il y a 62 ms entre mon phone et ma
tablette... Et puis ya mon phone qui me dis que c'est une appli pour une
vieille version android et gnagnagna, il est sur la 10.0 . j'ai eu une mise
à jour ce matin, avant il se plaignait pas ...

merci !
Al1
